---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - plcontainer.greenplum.org
  resources:
  - plcontainerbackends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plcontainer.greenplum.org
  resources:
  - plcontainerbackends/finalizers
  verbs:
  - update
- apiGroups:
  - plcontainer.greenplum.org
  resources:
  - plcontainerbackends/status
  verbs:
  - get
  - patch
  - update
