FROM python:3.7-slim-buster

RUN mkdir -p /clientdir

ENV PATH "${PATH:+:${PATH}}"
ENV LD_LIBRARY_PATH "/usr/lib/python3.7${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
ENV MANPATH "${MANPATH}"
ENV XDG_DATA_DIRS "${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
ENV PKG_CONFIG_PATH "${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}"
RUN python3.7 -m pip install nltk
RUN python3.7 -m nltk.downloader all
WORKDIR /clientdir
