#@ load("job_def.lib.yml",
#@   "entrance_job",
#@   "image_release_job",
#@   "build_test_job",
#@   "centos7_gpdb6_conf",
#@   "python_image_release_conf",
#@   "r_image_release_conf"
#@ )
#@ load("trigger_def.lib.yml",
#@   "release_trigger",
#@ )
#@
#@ load("base.lib.yml", "declare_res", "declare_res_type")
#@ res_map = {}
#@ res_type_map = {}
#@ trigger = release_trigger(res_map)
jobs:
#@ param = {
#@     "res_map": res_map,
#@     "trigger": trigger,
#@     "gpdb_src": "gpdb6_src",
#@     "conf": centos7_gpdb6_conf(release_build=True, is_bundle_release=True, container_name_suffix_python="python37.ubuntu1804_b", container_name_suffix_r="r.alpine")
#@ }
- #@ entrance_job(param)
- #@ build_test_job(param)
#@ param["rel_conf"] = python_image_release_conf()
- #@ image_release_job(param)
#@ param["rel_conf"] = r_image_release_conf()
- #@ image_release_job(param)

resources: #@ declare_res(res_type_map, res_map)

resource_types: #@ declare_res_type(res_type_map)
