#@ load("job_def.lib.yml",
#@   "entrance_job",
#@   "exit_release_job",
#@   "build_test_job",
#@   "centos7_gpdb6_conf",
#@   "rhel8_gpdb6_conf",
#@   "ubuntu18_gpdb6_conf")
#@ load("trigger_def.lib.yml",
#@   "release_trigger",
#@ )
#@
#@ load("base.lib.yml", "declare_res", "declare_res_type")
#@ res_map = {}
#@ res_type_map = {}
#@ trigger = release_trigger(res_map)
#@ confs = [
#@   centos7_gpdb6_conf(release_build=False, is_bundle_release=True, container_name_suffix_python="python37.ubuntu1804_b", container_name_suffix_r="r.alpine"),
#@   ubuntu18_gpdb6_conf(release_build=False, is_bundle_release=True, container_name_suffix_python="python37.ubuntu1804_b", container_name_suffix_r="r.alpine"),
#@   rhel8_gpdb6_conf(release_build=False, is_bundle_release=True, container_name_suffix_python="python37.ubuntu1804_b", container_name_suffix_r="r.alpine"),
#@ ]
jobs:
#@ param = {
#@     "res_map": res_map,
#@     "trigger": trigger,
#@ }
- #@ entrance_job(param)
#@ for conf in confs:
#@   param = {
#@     "res_map": res_map,
#@     "trigger": trigger,
#@     "gpdb_src": "gpdb6_src",
#@     "conf": conf
#@   }
- #@ build_test_job(param)
#@ end
#@ param = {
#@     "res_map": res_map,
#@     "trigger": trigger,
#@     "confs": confs
#@ }
- #@ exit_release_job(param)

resources: #@ declare_res(res_type_map, res_map)

resource_types: #@ declare_res_type(res_type_map)
