################################################################################
#################################### GROUPS ####################################
################################################################################

groups:
- name: plcontainer
  jobs:
  - plcontainer_build_centos6
  - plcontainer_build_centos7
  - set-pr-status

################################################################################
################################## RESOURCES ###################################
################################################################################
resource_types:
  - name: pull_request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
# Github Source Codes

- name: plcontainer_src
  type: pull_request
  source:
    repo: greenplum-db/plcontainer
    access_token: {{extension/github-access-token}}
    uri: https://github.com/greenplum-db/plcontainer.git

- name: gpdb_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/gpdb.git
    ignore_paths:
    - gpdb-doc/*
    - README*

# Docker images

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

- name: centos-gpdb-dev-7
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: 7-gcc6.2-llvm3.7

# S3 Input and intermediate binaries

- name: plr_gpdb5_centos6_build
  type: s3
  source:
    bucket: procedural-languages-concourse-gpdb-master
    region_name: us-west-2
    access_key_id: {{aws-bucket-access-key-id}}
    secret_access_key: {{aws-bucket-secret-access-key}}
    versioned_file: build/gpdb5/plr/centos6/plr-devel.gppkg
- name: plr_gpdb5_centos7_build
  type: s3
  source:
    bucket: procedural-languages-concourse-gpdb-master
    region_name: us-west-2
    access_key_id: {{aws-bucket-access-key-id}}
    secret_access_key: {{aws-bucket-secret-access-key}}
    versioned_file: build/gpdb5/plr/centos7/plr-devel.gppkg

- name: bin_gpdb_centos7
  type: s3
  source:
    access_key_id: {{aws-bucket-access-key-id}}
    bucket: gpdb5-assert-concourse-builds
    region_name: us-west-2
    secret_access_key: {{aws-bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos7/bin_gpdb.tar.gz

- name: bin_gpdb_centos6
  type: s3
  source:
    access_key_id: {{aws-bucket-access-key-id}}
    bucket: gpdb5-assert-concourse-builds
    region_name: us-west-2
    secret_access_key: {{aws-bucket-secret-access-key}}
    versioned_file: {{bin_gpdb_centos/bin_gpdb.tar.gz}}

- name: plcontainer_gpdb_centos7_build
  type: s3
  source:
    bucket: procedural-languages-concourse-gpdb-master
    region_name: us-west-2
    access_key_id: {{aws-bucket-access-key-id}}
    secret_access_key: {{aws-bucket-secret-access-key}}
    versioned_file: build/gpdb5/plcontainer/plcontainer-concourse-centos7.gppkg

- name: plcontainer_gpdb_centos6_build
  type: s3
  source:
    bucket: procedural-languages-concourse-gpdb-master
    region_name: us-west-2
    access_key_id: {{aws-bucket-access-key-id}}
    secret_access_key: {{aws-bucket-secret-access-key}}
    versioned_file: build/gpdb5/plcontainer/plcontainer-concourse-centos6.gppkg



##################################### JOBS #####################################
################################################################################

jobs:

# Build PL/Container GP Package
- name: plcontainer_build_centos6
  max_in_flight: 4
  plan:
  - aggregate:
    - get: bin_gpdb_centos6
    - get: gpdb_src
    - get: plcontainer_src
      trigger: true
      version: every
    - get: centos-gpdb-dev-6
    - get: plr
      resource: plr_gpdb5_centos6_build
  - task: plcontainer_gpdb_build
    file: plcontainer_src/concourse/tasks/plcontainer_build.yml
    image: centos-gpdb-dev-6
    input_mapping:
      bin_gpdb: bin_gpdb_centos6
  - aggregate:
    - put: plcontainer_gpdb_centos6_build
      params:
        file: plcontainer_gpdb_build/plcontainer-concourse.gppkg

- name: plcontainer_build_centos7
  max_in_flight: 4
  plan:
  - aggregate:
    - get: bin_gpdb_centos7
    - get: gpdb_src
    - get: plcontainer_src
      trigger: true
      version: every
    - get: centos-gpdb-dev-7
    - get: plr
      resource: plr_gpdb5_centos7_build
  - task: plcontainer_gpdb_build
    file: plcontainer_src/concourse/tasks/plcontainer_build.yml
    image: centos-gpdb-dev-7
    input_mapping:
      bin_gpdb: bin_gpdb_centos7
  - aggregate:
    - put: plcontainer_gpdb_centos7_build
      params:
        file: plcontainer_gpdb_build/plcontainer-concourse.gppkg

- name: set-pr-status
  plan:
  - aggregate:
    - get: plcontainer_src
      trigger: true
      version: every
      passed:
      - plcontainer_build_centos6
      - plcontainer_build_centos7
  - put: set_pr_success
    resource: plcontainer_src
    params:
      path: plcontainer_src
      status: success


