################################################################################
#################################### GROUPS ####################################
################################################################################

groups:
- name: plcontainer
  jobs:
  - plcontainer_release
  - plcontainer_function_test_centos7
  - plcontainer_resgroup_test_centos7
  - plcontainer_function_test_rhel8
  - plcontainer_resgroup_test_rhel8
  - plcontainer_function_test_ubuntu18
  - plcontainer_resgroup_test_ubuntu18

################################################################################
################################## RESOURCES ###################################
################################################################################
ccp_create_params_anchor: &ccp_default_params
  action: create
  delete_on_failure: true
  generate_random_name: true
  plugin_dir: ../../terraform.d/plugin-cache/linux_amd64
  terraform_source: ccp_src/google/

ccp_gen_cluster_default_params_anchor: &ccp_gen_cluster_default_params
  AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
  AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
  AWS_DEFAULT_REGION: {{aws-region}}
  BUCKET_PATH: clusters-google/
  BUCKET_NAME: {{tf-bucket-name}}
  CLOUD_PROVIDER: google

ccp_options_anchor6: &ccp_options6
  terraform_source: ccp_src/google/
  vars:
    instance_type: n1-standard-1
    platform: centos6

ccp_destroy_anchor: &ccp_destroy
  put: terraform
  params:
    action: destroy
    env_name_file: terraform/name
    plugin_dir: ../../terraform.d/plugin-cache/linux_amd64
    terraform_source: ccp_src/google/
    vars:
      aws_instance-node-instance_type: t2.micro #t2.micro is ignored in destroy, but aws_instance-node-instance_type is required.
      aws_ebs_volume_type: standard
  get_params:
    action: destroy


ccp_options_anchor7: &ccp_options7
  terraform_source: ccp_src/google/
  vars:
    instance_type: n1-standard-1
    platform: centos7

set_failed_anchor: &set_failed
  do:
  - task: on_failure_set_failed
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: gcr.io/data-gpdb-public-images/ccp
          tag: latest
      inputs:
        - name: ccp_src
        - name: terraform
      run:
        path: 'ccp_src/google/ccp_failed_test.sh'
      params:
        GOOGLE_CREDENTIALS: {{google-service-account-key}}
        GOOGLE_PROJECT_ID: {{google-project-id}}
        GOOGLE_ZONE: {{google-zone}}
        GOOGLE_SERVICE_ACCOUNT: {{google-service-account}}
        AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
        AWS_DEFAULT_REGION: {{tf-machine-region}}
        BUCKET_PATH: clusters-google/
        BUCKET_NAME: {{tf-bucket-name}}

## ======================================================================
## resource types
## ======================================================================

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.11.14

resources:

# Github Source Codes
- name: ccp_src
  type: git
  source:
    branch: {{ccp-git-branch}}
    private_key: {{ccp-git-key}}
    uri: {{ccp-git-remote}}

- name: plcontainer_src
  type: git
  source:
    branch: sa/6X_rhel8
    uri: https://github.com/greenplum-db/plcontainer.git
    tag_filter: 2.*

- name: gpdb_src
  type: git
  source:
    branch: 6X_STABLE
    uri: {{gpdb-git-remote}}
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: terraform
  type: terraform
  source:
    env:
      AWS_ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}
      GOOGLE_CREDENTIALS: {{google-service-account-key}}
    vars:
      project_id: {{google-project-id}}
    storage:
      access_key_id: {{tf-machine-access-key-id}}
      secret_access_key: {{tf-machine-secret-access-key}}
      region_name: {{aws-region}}
      # This is not parameterized, on purpose. All tfstates will go to this spot,
      # and different teams will place there clusters' tfstate files under different paths
      bucket: {{tf-bucket-name}}
      bucket_path: clusters-google/

- name: terraform.d
  source:
    access_key_id: ((bucket-access-key-id))
    bucket: ccp-terraform-provider-plugins
    region_name: ((aws-region))
    secret_access_key: ((bucket-secret-access-key))
    versioned_file: plugin-cache.tgz
  type: s3

# Docker images
- name: centos-gpdb-dev-7
  type: docker-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb5-centos7-build-test
    tag: latest

- name: ubuntu18-image
  type: docker-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb6-ubuntu18.04-build
    tag: latest

- name: rhel-image-test-8
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-private-images/gpdb6-rhel8-test
    tag: latest
    username: _json_key
    password: ((container-registry-readonly-service-account-key))

# GCS Input and intermediate binaries
- name: plcontainer_docker_image_python
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: plcontainer/released/gpdb6/plcontainer-python-image-(.*)-gp6.tar.gz

- name: plcontainer_docker_image_python3
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: plcontainer/released/gpdb6/plcontainer-python3-image-(.*)-gp6.tar.gz

- name: plcontainer_docker_image_r
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: plcontainer/released/gpdb6/plcontainer-r-image-(.*)-gp6.tar.gz

- name: plcontainer_docker_image_build_python
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: plcontainer/published/gpdb6/plcontainer-python-images-devel.tar.gz

- name: plcontainer_docker_image_build_python3
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: plcontainer/published/gpdb6/plcontainer-python3-images-devel.tar.gz

- name: plcontainer_docker_image_build_r
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: plcontainer/published/gpdb6/plcontainer-r-images-devel.tar.gz

- name: bin_gpdb_ubuntu18
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_ubuntu18.04/bin_gpdb.tar.gz

- name: bin_gpdb_centos7
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_centos7/bin_gpdb.tar.gz

- name: bin_gpdb_rhel8
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_rhel8/bin_gpdb.tar.gz

- name: plcontainer_gpdb_centos7_release
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: plcontainer/released/gpdb6/plcontainer-2.(.*)-rhel7_x86_64.gppkg

- name: plcontainer_gpdb_rhel8_release
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: plcontainer/released/gpdb6/plcontainer-2.(.*)-rhel8_x86_64.gppkg

- name: plcontainer_gpdb_ubuntu18_release
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: plcontainer/released/gpdb6/plcontainer-2.(.*)-ubuntu18.04_x86_64.gppkg

- name: plcontainer_gpdb_ubuntu18_build
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: plcontainer/published/gpdb6/plcontainer-concourse-ubuntu18.gppkg

- name: plcontainer_gpdb_centos7_build
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: plcontainer/published/gpdb6/plcontainer-concourse-centos7.gppkg

- name: plcontainer_gpdb_rhel8_build
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: plcontainer/published/gpdb6/plcontainer-concourse-rhel8.gppkg

##################################### JOBS #####################################
################################################################################

jobs:

# Release PL/Container GP Package
- name: plcontainer_release
  max_in_flight: 1
  plan:
  - aggregate:
    - get: plcontainer_gpdb_ubuntu18_build
    - get: plcontainer_gpdb_centos7_build
    - get: plcontainer_gpdb_rhel8_build
    - get: plcontainer_docker_image_build_python
    - get: plcontainer_docker_image_build_python3
    - get: plcontainer_docker_image_build_r
    - get: plcontainer_src  
    - get: centos-gpdb-dev-7
  - task: plcontainer_gpdb_build
    file: plcontainer_src/concourse/tasks/plcontainer_release.yml
    image: centos-gpdb-dev-7
  - aggregate:
    - put: plcontainer_gpdb_centos7_release
      params:
        file: release_bin_centos7/plcontainer-*.gppkg
    - put: plcontainer_gpdb_ubuntu18_release
      params:
        file: release_bin_ubuntu18/plcontainer-*.gppkg
    - put: plcontainer_gpdb_rhel8_release
      params:
        file: release_bin_rhel8/plcontainer-*.gppkg
    - put: plcontainer_docker_image_r
      params:
        file: release_image_r/plcontainer-*.tar.gz
    - put: plcontainer_docker_image_python
      params:
        file: release_image_python/plcontainer-*.tar.gz
    - put: plcontainer_docker_image_python3
      params:
        file: release_image_python3/plcontainer-*.tar.gz

- name: plcontainer_function_test_centos7
  plan:
  - aggregate:
    - get: plcontainer_src
    - get: gpdb_src
    - get: gpdb_binary
      resource: bin_gpdb_centos7
      trigger: true
    - get: ccp_src
    - get: terraform.d
      params:
        unpack: true
    - get: centos-gpdb-dev-7
    - get: plcontainer_pyclient_docker_image
      resource: plcontainer_docker_image_build_python
    - get: plcontainer_py3client_docker_image
      resource: plcontainer_docker_image_build_python3
    - get: plcontainer_rclient_docker_image
      resource: plcontainer_docker_image_build_r
    - get: plcontainer_gpdb_centos7_release
  - put: terraform
    params:
      <<: *ccp_default_params
      vars:
        instance_type: n1-standard-4
        PLATFORM: centos7
        disk_size: 100
        disk_type: pd-ssd
        zone: {{google-zone}}
        region: {{google-region}}
  - task: gen_cluster
    file: ccp_src/ci/tasks/gen_cluster.yml
    params:
      <<: *ccp_gen_cluster_default_params
      PLATFORM: centos7
  - task: gpinitsystem
    file: ccp_src/ci/tasks/gpinitsystem.yml
  - task: plcontainer
    file: plcontainer_src/concourse/tasks/plcontainer_tests.yml
    params:
      platform: centos7
    image: centos-gpdb-dev-7
    input_mapping:
      plcontainer_gpdb_build: plcontainer_gpdb_centos7_release
    on_success:
      <<: *ccp_destroy
  ensure:
    <<: *set_failed

- name: plcontainer_resgroup_test_centos7
  plan:
  - aggregate:
    - get: plcontainer_src
    - get: gpdb_src
    - get: gpdb_binary
      resource: bin_gpdb_centos7
      trigger: true
    - get: ccp_src
    - get: terraform.d
      params:
        unpack: true
    - get: centos-gpdb-dev-7
    - get: plcontainer_pyclient_docker_image
      resource: plcontainer_docker_image_build_python
    - get: plcontainer_rclient_docker_image
      resource: plcontainer_docker_image_build_r
    - get: plcontainer_gpdb_centos7_release
  - put: terraform
    params:
      <<: *ccp_default_params
      vars:
        instance_type: n1-standard-4
        PLATFORM: centos7
        disk_size: 100
        disk_type: pd-ssd
        zone: {{google-zone}}
        region: {{google-region}}
  - task: gen_cluster
    file: ccp_src/ci/tasks/gen_cluster.yml
    params:
      <<: *ccp_gen_cluster_default_params
      PLATFORM: centos7
  - task: gpinitsystem
    file: ccp_src/ci/tasks/gpinitsystem.yml
  - task: plcontainer_resgroup
    file: plcontainer_src/concourse/tasks/plcontainer_resgroup_tests.yml
    params:
      TEST_OS: centos7
      platform: centos7
    image: centos-gpdb-dev-7
    input_mapping:
      plcontainer_gpdb_build: plcontainer_gpdb_centos7_release
    on_success:
      <<: *ccp_destroy
  ensure:
    <<: *set_failed

- name: plcontainer_function_test_rhel8
  plan:
  - aggregate:
    - get: plcontainer_src
    - get: gpdb_src
    - get: gpdb_binary
      resource: bin_gpdb_rhel8
      trigger: true
    - get: ccp_src
    - get: terraform.d
      params:
        unpack: true
    - get: rhel-image-test-8
    - get: plcontainer_pyclient_docker_image
      resource: plcontainer_docker_image_python
    - get: plcontainer_py3client_docker_image
      resource: plcontainer_docker_image_python3
    - get: plcontainer_rclient_docker_image
      resource: plcontainer_docker_image_r
    - get: plcontainer_gpdb_rhel8_release
  - put: terraform
    params:
      <<: *ccp_default_params
      vars:
        instance_type: n1-standard-4
        PLATFORM: rhel8
        disk_size: 100
        disk_type: pd-ssd
        zone: {{google-zone}}
        region: {{google-region}}
  - task: gen_cluster
    file: ccp_src/ci/tasks/gen_cluster.yml
    params:
      <<: *ccp_gen_cluster_default_params
      PLATFORM: rhel8
  - task: gpinitsystem
    file: ccp_src/ci/tasks/gpinitsystem.yml
  - task: plcontainer
    file: plcontainer_src/concourse/tasks/plcontainer_tests.yml
    params:
      platform: rhel8
    image: rhel-image-test-8
    input_mapping:
      plcontainer_gpdb_build: plcontainer_gpdb_rhel8_release
    on_success:
      <<: *ccp_destroy
  ensure:
    <<: *set_failed

- name: plcontainer_resgroup_test_rhel8
  plan:
  - aggregate:
    - get: plcontainer_src
    - get: gpdb_src
    - get: gpdb_binary
      resource: bin_gpdb_rhel8
      trigger: true
    - get: ccp_src
    - get: terraform.d
      params:
        unpack: true
    - get: rhel-image-test-8
    - get: plcontainer_pyclient_docker_image
      resource: plcontainer_docker_image_python
    - get: plcontainer_rclient_docker_image
      resource: plcontainer_docker_image_r
    - get: plcontainer_gpdb_rhel8_release
  - put: terraform
    params:
      <<: *ccp_default_params
      vars:
        instance_type: n1-standard-4
        PLATFORM: rhel8
        disk_size: 100
        disk_type: pd-ssd
        zone: {{google-zone}}
        region: {{google-region}}
  - task: gen_cluster
    file: ccp_src/ci/tasks/gen_cluster.yml
    params:
      <<: *ccp_gen_cluster_default_params
      PLATFORM: rhel8
  - task: gpinitsystem
    file: ccp_src/ci/tasks/gpinitsystem.yml
  - task: plcontainer_resgroup
    file: plcontainer_src/concourse/tasks/plcontainer_resgroup_tests.yml
    params:
      TEST_OS: rhel8
      platform: rhel8
    image: rhel-image-test-8
    input_mapping:
      plcontainer_gpdb_build: plcontainer_gpdb_rhel8_release
    on_success:
      <<: *ccp_destroy
  ensure:
    <<: *set_failed
- name: plcontainer_function_test_ubuntu18
  plan:
  - aggregate:
    - get: plcontainer_src
    - get: gpdb_src
    - get: gpdb_binary
      resource: bin_gpdb_ubuntu18
      trigger: true
    - get: ccp_src
    - get: terraform.d
      params:
        unpack: true
    - get: ubuntu18-image
    - get: plcontainer_pyclient_docker_image
      resource: plcontainer_docker_image_build_python
    - get: plcontainer_py3client_docker_image
      resource: plcontainer_docker_image_build_python3
    - get: plcontainer_rclient_docker_image
      resource: plcontainer_docker_image_build_r
    - get: plcontainer_gpdb_ubuntu18_release
  - put: terraform
    params:
      <<: *ccp_default_params
      vars:
        instance_type: n1-standard-4
        PLATFORM: ubuntu18.04
        disk_size: 100
        disk_type: pd-ssd
        zone: {{google-zone}}
        region: {{google-region}}
  - task: gen_cluster
    file: ccp_src/ci/tasks/gen_cluster.yml
    params:
      <<: *ccp_gen_cluster_default_params
      PLATFORM: ubuntu18.04
  - task: gpinitsystem
    file: ccp_src/ci/tasks/gpinitsystem.yml
  - task: plcontainer
    file: plcontainer_src/concourse/tasks/plcontainer_tests.yml
    params:
      platform: ubuntu18
    image: ubuntu18-image
    input_mapping:
      plcontainer_gpdb_build: plcontainer_gpdb_ubuntu18_release
    on_success:
      <<: *ccp_destroy
  ensure:
    <<: *set_failed

- name: plcontainer_resgroup_test_ubuntu18
  plan:
  - aggregate:
    - get: plcontainer_src
    - get: gpdb_src
    - get: gpdb_binary
      resource: bin_gpdb_ubuntu18
      trigger: true
    - get: ccp_src
    - get: terraform.d
      params:
        unpack: true
    - get: ubuntu18-image
    - get: plcontainer_pyclient_docker_image
      resource: plcontainer_docker_image_build_python
    - get: plcontainer_rclient_docker_image
      resource: plcontainer_docker_image_build_r
    - get: plcontainer_gpdb_ubuntu18_release
  - put: terraform
    params:
      <<: *ccp_default_params
      vars:
        instance_type: n1-standard-4
        PLATFORM: ubuntu18.04
        disk_size: 100
        disk_type: pd-ssd
        zone: {{google-zone}}
        region: {{google-region}}
  - task: gen_cluster
    file: ccp_src/ci/tasks/gen_cluster.yml
    params:
      <<: *ccp_gen_cluster_default_params
      PLATFORM: ubuntu18.04
  - task: gpinitsystem
    file: ccp_src/ci/tasks/gpinitsystem.yml
  - task: plcontainer_resgroup
    file: plcontainer_src/concourse/tasks/plcontainer_resgroup_tests.yml
    params:
      TEST_OS: ubuntu18
      platform: ubuntu18
    image: ubuntu18-image
    input_mapping:
      plcontainer_gpdb_build: plcontainer_gpdb_ubuntu18_release
    on_success:
      <<: *ccp_destroy
  ensure:
    <<: *set_failed
